/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AuditLogs: () => import('#controllers/audit_logs_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Backups: () => import('#controllers/backups_controller'),
  Connections: () => import('#controllers/connections_controller'),
  DockerManager: () => import('#controllers/docker_manager_controller'),
  StorageDestinations: () => import('#controllers/storage_destinations_controller'),
  Storages: () => import('#controllers/storages_controller'),
  System: () => import('#controllers/system_controller'),
  Users: () => import('#controllers/users_controller'),
}
