//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "backups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub connection_id: Option<i64>,
    pub connection_database_id: Option<i64>,
    pub database_name: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub file_path: Option<String>,
    pub file_name: Option<String>,
    pub file_size: Option<i64>,
    pub checksum: Option<String>,
    pub compressed: Option<bool>,
    #[sea_orm(column_type = "Text")]
    pub retention_type: String,
    pub protected: Option<bool>,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    pub duration_seconds: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub exit_code: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub trigger: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub storage_destination_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::connection_databases::Entity",
        from = "Column::ConnectionDatabaseId",
        to = "super::connection_databases::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    ConnectionDatabases,
    #[sea_orm(
        belongs_to = "super::connections::Entity",
        from = "Column::ConnectionId",
        to = "super::connections::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Connections,
    #[sea_orm(
        belongs_to = "super::storage_destinations::Entity",
        from = "Column::StorageDestinationId",
        to = "super::storage_destinations::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    StorageDestinations,
}

impl Related<super::connection_databases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectionDatabases.def()
    }
}

impl Related<super::connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Connections.def()
    }
}

impl Related<super::storage_destinations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageDestinations.def()
    }
}
