//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "connection_databases")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_conn_db_unique")]
    pub connection_id: i64,
    #[sea_orm(unique_key = "idx_conn_db_unique")]
    pub database_name: String,
    pub enabled: Option<bool>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backups::Entity")]
    Backups,
    #[sea_orm(
        belongs_to = "super::connections::Entity",
        from = "Column::ConnectionId",
        to = "super::connections::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Connections,
}

impl Related<super::backups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Backups.def()
    }
}

impl Related<super::connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Connections.def()
    }
}
