// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldError } from "./FieldError";

/**
 * O corpo de **qualquer** falha da API.
 *
 * Os três campos são opcionais e mutuamente informativos, não alternativos:
 * um erro comum traz `error` + `description`; uma falha de validação traz
 * `errors`, com a lista de problemas de cada campo sob o nome dele.
 */
export type ApiErrorBody = { 
/**
 * Razão legível por máquina: `not_found`, `forbidden`, `unauthorized`…
 */
error: string | null, 
/**
 * Texto destinado a uma pessoa.
 */
description: string | null, 
/**
 * Presente só em falha de validação.
 */
errors: { [key in string]: Array<FieldError> } | null, };
