// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditActionCount } from "./AuditActionCount";
import type { AuditStatusCounts } from "./AuditStatusCounts";

/**
 * Corpo de `GET /api/audit-logs/stats`.
 */
export type AuditStats = { total: number, today: number, lastWeek: number, byStatus: AuditStatusCounts, byAction: Array<AuditActionCount>, };
