// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma entrada da trilha de auditoria.
 */
export type AuditLog = { id: number, action: string, 
/**
 * Tradução de `action` para exibição. `null` para uma ação desconhecida.
 */
actionDescription: string | null, 
/**
 * Ícone Material Design correspondente à ação.
 */
actionIcon: string | null, entityType: string, entityId: number | null, entityName: string | null, description: string, 
/**
 * Detalhes livres da operação — o diff de um update, por exemplo.
 */
details: unknown, status: string, 
/**
 * Cor com que a interface pinta o status.
 */
statusColor: string | null, errorMessage: string | null, ipAddress: string | null, createdAt: string, 
/**
 * Preenchido só no detalhe: são até 500 caracteres por linha, e cinquenta
 * deles por página inflariam a listagem sem que a tela de lista o mostre.
 */
userAgent: string | null, };
