// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma linha de `byAction`.
 */
export type AuditActionCount = { action: string, description: string | null, count: number, };
