// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `byStatus`.
 */
export type AuditStatusCounts = { success: number, failure: number, };
