// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conexão aninhada num item de backup.
 *
 * Quatro campos, e não o registro inteiro: é o que a lista de backups mostra
 * em cada linha, e trazer as credenciais junto exporia dado sensível numa
 * resposta que nem a tela usa.
 */
export type BackupConnection = { id: number, name: string, type: string, host: string, };
