// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupConnection } from "./BackupConnection";

/**
 * Um backup como a API o devolve.
 */
export type Backup = { id: number, connectionId: number | null, connectionDatabaseId: number | null, databaseName: string, storageDestinationId: number | null, status: string, filePath: string | null, fileName: string | null, fileSize: number | null, checksum: string | null, compressed: boolean, retentionType: string, 
/**
 * Um backup protegido não é apagado pela retenção nem pela rota de delete.
 */
protected: boolean, startedAt: string | null, finishedAt: string | null, durationSeconds: number | null, errorMessage: string | null, exitCode: number | null, 
/**
 * JSON já decodificado — a coluna guarda texto, e devolver a string crua
 * obrigaria o frontend a um `JSON.parse` que ele não faz.
 */
metadata: Record<string, unknown>, trigger: string, createdAt: string, updatedAt: string, 
/**
 * `null` quando o backup ficou órfão pelo `SET NULL` da chave estrangeira.
 */
connection: BackupConnection | null, };
