// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resposta de `GET|PUT /api/system/backup-retention`.
 */
export type BackupRetentionPolicy = { daily: number, weekly: number, monthly: number, yearly: number, pruneCron: string, defaultPruneCron: string, };
