// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseObject } from "./BrowseObject";

/**
 * Corpo de `GET /api/storages/:id/browse`.
 */
export type BrowseResult = { objects: Array<BrowseObject>, nextCursor: string | null, isTruncated: boolean, };
