// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageReplica } from "./StorageReplica";

/**
 * Um objeto na resposta de `browse`.
 *
 * `replicas` é sempre uma lista, vazia quando o arquivo só existe aqui — a
 * interface desenha o marcador de cópia a partir do tamanho dela, e uma chave
 * que às vezes falta obrigaria cada leitura a um teste de presença antes.
 */
export type BrowseObject = { key: string, name: string, 
/**
 * `null` em diretório — pasta não tem tamanho próprio.
 */
size: number | null, lastModified: string | null, isDirectory: boolean, etag: string | null, replicas: Array<StorageReplica>, };
