// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionBackupItem } from "./ConnectionBackupItem";

/**
 * Corpo de `POST /api/connections/:id/backup`.
 */
export type ConnectionBackupResult = { totalDatabases: number, successful: number, failed: number, backups: Array<ConnectionBackupItem>, };
