// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um database que a conexão acompanha.
 */
export type ConnectionDatabase = { id: number, databaseName: string, 
/**
 * Um database desabilitado continua na tabela e sai do próximo backup.
 */
enabled: boolean, };
