// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contadores de um recurso.
 */
export type ConnectionCounts = { total: number, active: number, };
