// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionDatabase } from "./ConnectionDatabase";

/**
 * Uma conexão e os databases que ela acompanha.
 */
export type Connection = { id: number, name: string, type: string, host: string, port: number, username: string, scheduleFrequency: string | null, scheduleEnabled: boolean, status: string | null, 
/**
 * Motivo da última falha de teste. `null` quando o último teste passou.
 */
lastError: string | null, lastTestedAt: string | null, lastBackupAt: string | null, storageDestinationId: number | null, 
/**
 * A coluna é JSON livre; estas são as duas chaves que a validação aceita.
 */
options: { ssl?: boolean; charset?: string } | null, createdAt: string, updatedAt: string, databases: Array<ConnectionDatabase>, };
