// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backup como a tela de histórico de uma conexão o mostra.
 */
export type ConnectionBackupDetail = { id: number, status: string, fileName: string | null, fileSize: number | null, databaseName: string, retentionType: string, trigger: string, createdAt: string, finishedAt: string | null, durationSeconds: number | null, };
