// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corpo de `POST /api/connections/:id/test` bem-sucedido.
 */
export type ConnectionTestResult = { latencyMs: number, version: string | null, };
