// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resultado do backup de **um** database dentro de
 * `POST /api/connections/:id/backup`.
 *
 * Uma forma só para sucesso e falha, com `success` dizendo qual é. Havia duas
 * formas que não compartilhavam chave nenhuma, e o cliente precisava descobrir
 * qual recebera testando a presença de campos — num contrato tipado isso vira
 * uma união que não estreita.
 *
 * `fileSize` e `durationSeconds` saem em bytes e segundos. Formatar (`1.50 MB`)
 * é decisão de apresentação, e o mesmo nome de campo não pode ser número numa
 * resposta e texto noutra.
 */
export type ConnectionBackupItem = { databaseName: string, backupId: number, success: boolean, fileName: string | null, fileSize: number | null, durationSeconds: number | null, 
/**
 * Preenchido só quando `success` é `false`.
 */
error: string | null, };
