// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backup resumido, como aparece na listagem de conexões.
 */
export type ConnectionBackupSummary = { id: number, status: string, fileSize: number | null, databaseName: string, createdAt: string, finishedAt: string | null, };
