// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionBackupSummary } from "./ConnectionBackupSummary";
import type { ConnectionDatabase } from "./ConnectionDatabase";

/**
 * Item de `GET /api/connections`.
 */
export type ConnectionListItem = { 
/**
 * Só o backup mais recente — a listagem mostra "último backup", e trazer o
 * histórico inteiro de cada linha multiplicaria a resposta pelo número de
 * backups já feitos.
 */
backups: Array<ConnectionBackupSummary>, id: number, name: string, 
/**
 * A migration-level `CHECK` limits this column to the three supported
 * database engines, so the generated contract can truthfully expose a
 * discriminating union instead of an arbitrary string.
 */
type: "mysql" | "mariadb" | "postgresql", host: string, port: number, username: string, scheduleFrequency: string | null, scheduleEnabled: boolean, status: string | null, 
/**
 * Motivo da última falha de teste. `null` quando o último teste passou.
 */
lastError: string | null, lastTestedAt: string | null, lastBackupAt: string | null, storageDestinationId: number | null, 
/**
 * A coluna é JSON livre; estas são as duas chaves que a validação aceita.
 */
options: { ssl?: boolean; charset?: string } | null, createdAt: string, updatedAt: string, databases: Array<ConnectionDatabase>, };
