// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corpo de `POST /api/connections/discover-databases`.
 */
export type DiscoveredDatabases = { databases: Array<string>, };
