// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostSuggestion } from "./HostSuggestion";

/**
 * Corpo de `GET /api/connections/docker-hosts`.
 *
 * Responde 200 mesmo sem Docker: a tela de nova conexão trata a ausência
 * mostrando o formulário manual, e um erro a faria exibir uma falha onde não
 * há nenhuma.
 */
export type DockerHosts = { dockerAvailable: boolean, unavailableReason: string | null, backendContainerId: string | null, hosts: Array<HostSuggestion>, };
