// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um problema encontrado num campo.
 */
export type FieldError = { 
/**
 * Nome da regra que falhou: `required`, `length`, `email`, `enum`…
 */
code: string, message: string | null, 
/**
 * O que a regra esperava — `min`, `max`, `choices`. Omitido quando vazio.
 *
 * **Nunca** o valor enviado: ver `controllers::validation_failed`.
 */
params?: Record<string, unknown>, };
