// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Origem do host sugerido.
 */
export type HostResolutionSource = "docker_dns" | "host_ip" | "fallback";
