// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostResolutionSource } from "./HostResolutionSource";
import type { PortOption } from "./PortOption";

/**
 * Sugestao final para um container.
 *
 * Serializa direto para o payload de `GET /api/connections/docker-hosts`: o
 * `rename_all` ja' produz o camelCase que o frontend espera, e o binding
 * `ts-rs` e' gerado a partir desta struct. Havia uma funcao que remontava o
 * mesmo objeto campo a campo com `json!` — duas descricoes do mesmo formato,
 * e nada obrigando as duas a concordarem.
 */
export type HostSuggestion = { containerId: string, containerName: string, databaseTypeHint: "mysql" | "mariadb" | "postgresql" | null, sameNetwork: boolean, suggestedHost: string, hostResolutionSource: HostResolutionSource, networkNames: Array<string>, portOptions: Array<PortOption>, recommendedPort: number | null, hasExternalPort: boolean, connectivityWarning: string | null, };
