// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Formatos aceitos, ja' canonizados.
 */
export type ImportedFormat = "sql" | "sql.gz" | "dump" | "zip" | "tar";
