// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backup } from "./Backup";
import type { ImportedFormat } from "./ImportedFormat";
import type { IntegrityResult } from "./IntegrityResult";

/**
 * Corpo de `POST /api/backups/import`.
 */
export type ImportedBackup = { backup: Backup, format: ImportedFormat, checksum: string, fileSize: number, 
/**
 * `null` quando a verificação de integridade não foi pedida.
 */
integrity: IntegrityResult | null, };
