// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resultado de uma verificacao de integridade.
 */
export type IntegrityResult = { valid: boolean, message: string, 
/**
 * `null` quando a verificacao nao produziu aviso.
 */
warnings: Array<string> | null, };
