// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Jobs = { isRunning: boolean, activeJobs: number, 
/**
 * Derivado de `is_running` — nunca gravado à parte, ou os dois campos
 * poderiam discordar.
 */
status: "ok" | "down", };
