// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De onde veio o numero de memoria.
 *
 * Dentro de um container o total de memoria do sistema e' o do **host**, nao o
 * limite do container — um painel lendo isso mostraria 3% de uso enquanto o
 * processo e' morto por OOM. Por isso a leitura prefere o cgroup, e a origem
 * sai na resposta para que a diferenca seja visivel na tela.
 */
export type MemorySource = "cgroup" | "os";
