// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostMemory } from "./HostMemory";
import type { MemorySource } from "./MemorySource";

export type Memory = { totalBytes: number, usedBytes: number, freeBytes: number, usagePercent: number, source: MemorySource, containerLimited: boolean, host: HostMemory | null, };
