// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O bloco `pagination` de uma página.
 */
export type PageInfo = { page: number, page_size: number, total_pages: number, total_items: number, };
