// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageInfo } from "./PageInfo";

/**
 * Uma página de resultados — o corpo de toda listagem.
 *
 * As chaves de `pagination` estão em snake_case porque é assim que o
 * `PagerMeta` do Loco serializa. Renomear aqui criaria dois vocabulários para
 * a mesma coisa, e o binding deixaria de descrever a resposta real.
 */
export type Paginated<T> = { results: Array<T>, pagination: PageInfo, };
