// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Item de `recentBackups`.
 */
export type RecentBackup = { id: number, 
/**
 * `"N/A"` quando a conexão foi apagada: a FK é `SET NULL`, e o painel
 * mostra o nome sem ter para onde navegar.
 */
connectionName: string, status: string, fileSize: number | null, createdAt: string, };
