// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cpu } from "./Cpu";
import type { Memory } from "./Memory";

export type Resources = { cpu: Cpu, memory: Memory, };
