// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corpo de `POST /api/backups/:id/restore`.
 *
 * A restauração é assíncrona: a resposta confirma o aceite e devolve o
 * identificador pelo qual o progresso chega no fluxo de eventos.
 */
export type RestoreAccepted = { restoreId: string, databaseName: string, };
