// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

/**
 * Corpo de `register` e `login` bem-sucedidos.
 */
export type Session = { 
/**
 * Sempre `"bearer"` — o cliente só repassa o valor no cabeçalho
 * `Authorization`. Vai ao TypeScript como tipo literal, e não como
 * `string`, para que um `Authorization: ${type}` errado não compile.
 */
type: "bearer", token: string, user: User, };
