// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupCounts } from "./BackupCounts";
import type { ConnectionCounts } from "./ConnectionCounts";
import type { RecentBackup } from "./RecentBackup";
import type { StorageSpace } from "./StorageSpace";
import type { SystemOverview } from "./SystemOverview";

/**
 * Corpo de `GET /api/stats`.
 */
export type Stats = { connections: ConnectionCounts, backups: BackupCounts, recentBackups: Array<RecentBackup>, storageSpaces: Array<StorageSpace>, system: SystemOverview, };
