// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uma cópia do mesmo arquivo em outro destino.
 */
export type StorageReplica = { locationType: string, storageId: number | null, storageName: string, provider: string, path: string, };
