// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Detalhe da rota legada.
 */
export type StorageDestinationDetail = { config: Record<string, unknown>, id: number, name: string, type: "local" | "s3" | "gcs" | "azure_blob" | "sftp", status: "active" | "inactive", isDefault: boolean, createdAt: string, updatedAt: string, };
