// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Item de `GET /api/storage-destinations` — sem `provider`.
 */
export type StorageDestination = { id: number, name: string, type: "local" | "s3" | "gcs" | "azure_blob" | "sftp", status: "active" | "inactive", isDefault: boolean, createdAt: string, updatedAt: string, };
