// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Item de `GET /api/storages`.
 */
export type Storage = { id: number, name: string, type: string, 
/**
 * Valor **cru** da coluna, que pode ser `null` em linha antiga.
 */
provider: string | null, providerLabel: string, status: string, isDefault: boolean, createdAt: string, updatedAt: string, };
