// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Espaço usado e livre de um destino.
 *
 * `type` sai como texto cru da coluna, e não como enum: o campo alimenta a
 * legenda da barra de uso, e uma linha com `type` desconhecido continua sendo
 * exibida em vez de sumir da lista.
 */
export type StorageSpace = { destinationId: number | null, destinationName: string, type: string, spaceAvailable: boolean, totalBytes: number, usedBytes: number, freeBytes: number, usedPercent: number, freePercent: number, isLowSpace: boolean, lowSpaceThreshold: number, };
