// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Detalhe da rota legada.
 */
export type StorageDestinationDetail = { config: Record<string, unknown>, id: number, name: string, type: string, status: string, isDefault: boolean, createdAt: string, updatedAt: string, };
