// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET`/`POST`/`PUT` de um storage — o item mais a config mascarada.
 */
export type StorageDetail = { 
/**
 * Já passou por `safeConfig`: nenhum segredo sai daqui.
 */
config: Record<string, unknown>, id: number, name: string, type: string, 
/**
 * Valor **cru** da coluna, que pode ser `null` em linha antiga.
 */
provider: string | null, providerLabel: string, status: string, isDefault: boolean, createdAt: string, updatedAt: string, };
