// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estado do sistema para a tela de primeiro acesso.
 */
export type SystemStatus = { hasUsers: boolean, 
/**
 * `true` só quando **não há nenhum usuário** e o ambiente é produção.
 *
 * É o que faz a tela de cadastro pedir o token de bootstrap. Fora de
 * produção o primeiro administrador é criado sem token, para não travar o
 * desenvolvimento.
 */
requiresBootstrapToken: boolean, };
