// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Jobs } from "./Jobs";
import type { Resources } from "./Resources";

/**
 * Cabecalho de `GET /api/system/status`.
 *
 * `runtimeVersion` identifica o runtime que esta' respondendo — a versao do
 * Rust com que o binario foi compilado.
 */
export type SystemOverview = { version: string, hostname: string, platform: string, architecture: string, runtimeVersion: string, uptimeSeconds: number, resources: Resources, jobs: Jobs, };
