// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Um usuário como a API o devolve.
 *
 * A senha **não** está aqui, e nunca pode estar: `GET /api/users` lista todo
 * mundo, então um vazamento exporia o hash de todos de uma vez, não só o de
 * quem chamou. O mesmo vale para `api_key` e para os tokens de recuperação —
 * são credenciais, não atributos de perfil.
 */
export type User = { id: number, fullName: string | null, email: string, isActive: boolean, isAdmin: boolean, createdAt: string, updatedAt: string, };
