// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corpo de `PATCH /api/users/:id/status` — só o que mudou.
 *
 * Devolver o usuário inteiro seria mais uniforme, mas esta rota existe para
 * alternar um campo: o cliente que a chama quer confirmar o novo estado, e
 * tudo o mais que viesse junto seria dado que ele já tem.
 */
export type UserStatus = { id: number, isActive: boolean, };
