//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "connections")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub host: String,
    pub port: i64,
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub password_encrypted: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub schedule_frequency: Option<String>,
    pub schedule_enabled: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub last_tested_at: Option<DateTimeWithTimeZone>,
    pub last_backup_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub options: Option<String>,
    pub storage_destination_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backups::Entity")]
    Backups,
    #[sea_orm(has_many = "super::connection_databases::Entity")]
    ConnectionDatabases,
    #[sea_orm(
        belongs_to = "super::storage_destinations::Entity",
        from = "Column::StorageDestinationId",
        to = "super::storage_destinations::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    StorageDestinations,
}

impl Related<super::backups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Backups.def()
    }
}

impl Related<super::connection_databases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectionDatabases.def()
    }
}

impl Related<super::storage_destinations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageDestinations.def()
    }
}
