//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub full_name: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub is_active: bool,
    pub is_admin: bool,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auth_access_tokens::Entity")]
    AuthAccessTokens,
}

impl Related<super::auth_access_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthAccessTokens.def()
    }
}
