/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'description', 'details', 'entityId', 'entityName', 'entityType', 'errorMessage', 'id', 'ipAddress', 'status', 'userAgent'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare details: string | null
  @column()
  declare entityId: number | null
  @column()
  declare entityName: string | null
  @column()
  declare entityType: string
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare status: string
  @column()
  declare userAgent: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BackupSchema extends BaseModel {
  static $columns = ['checksum', 'compressed', 'connectionDatabaseId', 'connectionId', 'createdAt', 'databaseName', 'durationSeconds', 'errorMessage', 'exitCode', 'fileName', 'filePath', 'fileSize', 'finishedAt', 'id', 'metadata', 'protected', 'retentionType', 'startedAt', 'status', 'storageDestinationId', 'trigger', 'updatedAt'] as const
  $columns = BackupSchema.$columns
  @column()
  declare checksum: string | null
  @column()
  declare compressed: boolean | null
  @column()
  declare connectionDatabaseId: number | null
  @column()
  declare connectionId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare databaseName: string
  @column()
  declare durationSeconds: number | null
  @column()
  declare errorMessage: string | null
  @column()
  declare exitCode: number | null
  @column()
  declare fileName: string | null
  @column()
  declare filePath: string | null
  @column()
  declare fileSize: bigint | number | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: string | null
  @column()
  declare protected: boolean | null
  @column()
  declare retentionType: string
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare storageDestinationId: number | null
  @column()
  declare trigger: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ConnectionDatabaseSchema extends BaseModel {
  static $columns = ['connectionId', 'createdAt', 'databaseName', 'enabled', 'id', 'updatedAt'] as const
  $columns = ConnectionDatabaseSchema.$columns
  @column()
  declare connectionId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare databaseName: string
  @column()
  declare enabled: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ConnectionSchema extends BaseModel {
  static $columns = ['createdAt', 'host', 'id', 'lastBackupAt', 'lastError', 'lastTestedAt', 'name', 'options', 'passwordEncrypted', 'port', 'scheduleEnabled', 'scheduleFrequency', 'status', 'storageDestinationId', 'type', 'updatedAt', 'username'] as const
  $columns = ConnectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare host: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastBackupAt: DateTime | null
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastTestedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare options: string | null
  @column()
  declare passwordEncrypted: string
  @column()
  declare port: number
  @column()
  declare scheduleEnabled: boolean | null
  @column()
  declare scheduleFrequency: string | null
  @column()
  declare status: string | null
  @column()
  declare storageDestinationId: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}

export class ResourceMetricHistorySchema extends BaseModel {
  static $columns = ['collectedAt', 'cpuUsagePercent', 'createdAt', 'entityId', 'entityName', 'id', 'memoryTotalBytes', 'memoryUsagePercent', 'memoryUsedBytes', 'scope', 'updatedAt'] as const
  $columns = ResourceMetricHistorySchema.$columns
  @column.dateTime()
  declare collectedAt: DateTime
  @column()
  declare cpuUsagePercent: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string | null
  @column()
  declare entityName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare memoryTotalBytes: bigint | number
  @column()
  declare memoryUsagePercent: number
  @column()
  declare memoryUsedBytes: bigint | number
  @column()
  declare scope: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class StorageDestinationSchema extends BaseModel {
  static $columns = ['configEncrypted', 'createdAt', 'id', 'isDefault', 'name', 'provider', 'status', 'type', 'updatedAt'] as const
  $columns = StorageDestinationSchema.$columns
  @column()
  declare configEncrypted: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare provider: string | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SystemSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt', 'value'] as const
  $columns = SystemSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'isAdmin', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isAdmin: boolean
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
