/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NotificationToast: typeof import('./components/NotificationToast.vue')['default']
    ReloadPrompt: typeof import('./components/common/ReloadPrompt.vue')['default']
    RestoreProgressOverlay: typeof import('./components/RestoreProgressOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
