/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchiveProgress: typeof import('./components/storages/ArchiveProgress.vue')['default']
    BucketExplorer: typeof import('./components/storages/BucketExplorer.vue')['default']
    ContainerCard: typeof import('./components/docker/ContainerCard.vue')['default']
    ContainerEnvironmentTable: typeof import('./components/docker/ContainerEnvironmentTable.vue')['default']
    ContainerLogsViewer: typeof import('./components/docker/ContainerLogsViewer.vue')['default']
    ContainerMountsTable: typeof import('./components/docker/ContainerMountsTable.vue')['default']
    ContainerNetworkDialog: typeof import('./components/docker/ContainerNetworkDialog.vue')['default']
    ContainerNetworkTable: typeof import('./components/docker/ContainerNetworkTable.vue')['default']
    ContainerPortsTable: typeof import('./components/docker/ContainerPortsTable.vue')['default']
    ContainerProjectGroup: typeof import('./components/docker/ContainerProjectGroup.vue')['default']
    ContainerRemoveDialog: typeof import('./components/docker/ContainerRemoveDialog.vue')['default']
    ContainerStatusChip: typeof import('./components/docker/ContainerStatusChip.vue')['default']
    CopyJobProgress: typeof import('./components/storages/CopyJobProgress.vue')['default']
    CreateDatabaseDialog: typeof import('./components/common/CreateDatabaseDialog.vue')['default']
    DockerActionConfirmDialog: typeof import('./components/docker/DockerActionConfirmDialog.vue')['default']
    DockerContainerResourceCard: typeof import('./components/system/DockerContainerResourceCard.vue')['default']
    DockerContainerResourceCharts: typeof import('./components/system/DockerContainerResourceCharts.vue')['default']
    DockerUnavailableBanner: typeof import('./components/docker/DockerUnavailableBanner.vue')['default']
    FileDropZone: typeof import('./components/backups/FileDropZone.vue')['default']
    HostSelectorField: typeof import('./components/connections/HostSelectorField.vue')['default']
    ImageCard: typeof import('./components/docker/ImageCard.vue')['default']
    ImageDetailDialog: typeof import('./components/docker/ImageDetailDialog.vue')['default']
    ImportBackupDialog: typeof import('./components/backups/ImportBackupDialog.vue')['default']
    NetworkCard: typeof import('./components/docker/NetworkCard.vue')['default']
    NetworkDetailDialog: typeof import('./components/docker/NetworkDetailDialog.vue')['default']
    NotificationToast: typeof import('./components/NotificationToast.vue')['default']
    RestoreDialog: typeof import('./components/backups/RestoreDialog.vue')['default']
    RestoreProgressOverlay: typeof import('./components/RestoreProgressOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StorageFormFields: typeof import('./components/storages/StorageFormFields.vue')['default']
    StorageProviderIcon: typeof import('./components/storages/StorageProviderIcon.vue')['default']
    StorageTestButton: typeof import('./components/storages/StorageTestButton.vue')['default']
    SystemInfoCard: typeof import('./components/system/SystemInfoCard.vue')['default']
    SystemResourceCharts: typeof import('./components/system/SystemResourceCharts.vue')['default']
    UsageLineChart: typeof import('./components/system/UsageLineChart.vue')['default']
    VolumeBackupDialog: typeof import('./components/docker/VolumeBackupDialog.vue')['default']
    VolumeCard: typeof import('./components/docker/VolumeCard.vue')['default']
    VolumeDetailDialog: typeof import('./components/docker/VolumeDetailDialog.vue')['default']
  }
}
