/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/audit/': RouteRecordInfo<'/audit/', '/audit', Record<never, never>, Record<never, never>>,
    '/backups/': RouteRecordInfo<'/backups/', '/backups', Record<never, never>, Record<never, never>>,
    '/connections/': RouteRecordInfo<'/connections/', '/connections', Record<never, never>, Record<never, never>>,
    '/connections/[id]': RouteRecordInfo<'/connections/[id]', '/connections/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/storages/': RouteRecordInfo<'/storages/', '/storages', Record<never, never>, Record<never, never>>,
    '/storages/[id]/': RouteRecordInfo<'/storages/[id]/', '/storages/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/storages/[id]/copy': RouteRecordInfo<'/storages/[id]/copy', '/storages/:id/copy', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/storages/[id]/download': RouteRecordInfo<'/storages/[id]/download', '/storages/:id/download', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/storages/[id]/explore': RouteRecordInfo<'/storages/[id]/explore', '/storages/:id/explore', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/storages/new': RouteRecordInfo<'/storages/new', '/storages/new', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/audit/index.vue': {
      routes: '/audit/'
      views: never
    }
    'src/pages/backups/index.vue': {
      routes: '/backups/'
      views: never
    }
    'src/pages/connections/index.vue': {
      routes: '/connections/'
      views: never
    }
    'src/pages/connections/[id].vue': {
      routes: '/connections/[id]'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
    'src/pages/settings/index.vue': {
      routes: '/settings/'
      views: never
    }
    'src/pages/storages/index.vue': {
      routes: '/storages/'
      views: never
    }
    'src/pages/storages/[id]/index.vue': {
      routes: '/storages/[id]/'
      views: never
    }
    'src/pages/storages/[id]/copy.vue': {
      routes: '/storages/[id]/copy'
      views: never
    }
    'src/pages/storages/[id]/download.vue': {
      routes: '/storages/[id]/download'
      views: never
    }
    'src/pages/storages/[id]/explore.vue': {
      routes: '/storages/[id]/explore'
      views: never
    }
    'src/pages/storages/new.vue': {
      routes: '/storages/new'
      views: never
    }
    'src/pages/users/index.vue': {
      routes: '/users/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
