CREATE TABLE `adonis_schema` (`id` integer not null primary key autoincrement, `name` varchar(255) not null, `batch` integer not null, `migration_time` datetime default CURRENT_TIMESTAMP);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE `adonis_schema_versions` (`version` integer, primary key (`version`));
CREATE TABLE `connection_databases` (`id` integer not null primary key autoincrement, `connection_id` integer not null, `database_name` varchar(100) not null, `enabled` boolean default '1', `created_at` datetime not null, `updated_at` datetime not null, foreign key(`connection_id`) references `connections`(`id`) on delete CASCADE);
CREATE INDEX `idx_conn_db_connection` on `connection_databases` (`connection_id`);
CREATE INDEX `idx_conn_db_connection_enabled` on `connection_databases` (`connection_id`, `enabled`);
CREATE UNIQUE INDEX `idx_conn_db_unique` on `connection_databases` (`connection_id`, `database_name`);
CREATE TABLE `storage_destinations` (`id` integer not null primary key autoincrement, `name` varchar(100) not null, `type` text check (`type` in ('local', 's3', 'gcs', 'azure_blob', 'sftp')) not null, `status` text check (`status` in ('active', 'inactive')) not null default 'active', `is_default` boolean not null default '0', `config_encrypted` text not null, `created_at` datetime not null, `updated_at` datetime not null, `provider` varchar(50) null);
CREATE INDEX `idx_storage_destinations_type` on `storage_destinations` (`type`);
CREATE INDEX `idx_storage_destinations_status` on `storage_destinations` (`status`);
CREATE INDEX `idx_storage_destinations_is_default` on `storage_destinations` (`is_default`);
CREATE TABLE IF NOT EXISTS "connections" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` varchar(100) NOT NULL, `type` text NOT NULL CHECK (`type` in('mysql' , 'mariadb' , 'postgresql')), `host` varchar(255) NOT NULL, `port` integer NOT NULL, `username` varchar(100) NOT NULL, `password_encrypted` text NOT NULL, `schedule_frequency` text NULL CHECK (`schedule_frequency` in('1h' , '6h' , '12h' , '24h')), `schedule_enabled` boolean DEFAULT '0', `status` text CHECK (`status` in('active' , 'inactive' , 'error')) DEFAULT 'active', `last_error` text NULL, `last_tested_at` datetime NULL, `last_backup_at` datetime NULL, `options` text NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `storage_destination_id` integer NULL, FOREIGN KEY (`storage_destination_id`) REFERENCES `storage_destinations` (`id`) ON DELETE SET NULL);
CREATE INDEX `idx_connections_type` on `connections` (`type`);
CREATE INDEX `idx_connections_status` on `connections` (`status`);
CREATE INDEX `idx_connections_schedule` on `connections` (`schedule_enabled`);
CREATE INDEX `idx_connections_storage_destination` on `connections` (`storage_destination_id`);
CREATE INDEX `idx_storage_destinations_provider` on `storage_destinations` (`provider`);
CREATE TABLE IF NOT EXISTS "backups" (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `connection_id` integer, `connection_database_id` integer NULL, `database_name` varchar(100) NOT NULL, `status` text NOT NULL CHECK (`status` in('pending' , 'running' , 'completed' , 'failed' , 'cancelled')) DEFAULT 'pending', `file_path` varchar(500) NULL, `file_name` varchar(255) NULL, `file_size` bigint NULL, `checksum` varchar(64) NULL, `compressed` boolean DEFAULT '1', `retention_type` text NOT NULL CHECK (`retention_type` in('hourly' , 'daily' , 'weekly' , 'monthly' , 'yearly')) DEFAULT 'hourly', `protected` boolean DEFAULT '0', `started_at` datetime NULL, `finished_at` datetime NULL, `duration_seconds` integer NULL, `error_message` text NULL, `exit_code` integer NULL, `metadata` text NULL, `trigger` text NOT NULL CHECK (`trigger` in('scheduled' , 'manual')) DEFAULT 'manual', `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `storage_destination_id` integer NULL, FOREIGN KEY (`connection_id`) REFERENCES `connections` (`id`) ON DELETE CASCADE, FOREIGN KEY (`connection_database_id`) REFERENCES `connection_databases` (`id`) ON DELETE SET NULL, FOREIGN KEY (`storage_destination_id`) REFERENCES `storage_destinations` (`id`) ON DELETE SET NULL, FOREIGN KEY (`connection_id`) REFERENCES `connections` (`id`) ON DELETE CASCADE);
CREATE INDEX `idx_backups_connection` on `backups` (`connection_id`);
CREATE INDEX `idx_backups_conn_database` on `backups` (`connection_database_id`);
CREATE INDEX `idx_backups_database_name` on `backups` (`database_name`);
CREATE INDEX `idx_backups_status` on `backups` (`status`);
CREATE INDEX `idx_backups_retention` on `backups` (`retention_type`);
CREATE INDEX `idx_backups_created` on `backups` (`created_at`);
CREATE INDEX `idx_backups_connection_status` on `backups` (`connection_id`, `status`);
CREATE INDEX `idx_backups_retention_protected` on `backups` (`retention_type`, `protected`);
CREATE INDEX `idx_backups_storage_destination` on `backups` (`storage_destination_id`);
CREATE TABLE `resource_metric_history` (`id` integer not null primary key autoincrement, `scope` text check (`scope` in ('system', 'container')) not null, `entity_id` varchar(128) null, `entity_name` varchar(255) null, `cpu_usage_percent` float not null, `memory_usage_percent` float not null, `memory_used_bytes` bigint not null, `memory_total_bytes` bigint not null, `collected_at` datetime not null, `created_at` datetime not null, `updated_at` datetime not null);
CREATE INDEX `idx_resource_metric_history_scope_collected_at` on `resource_metric_history` (`scope`, `collected_at`);
CREATE INDEX `idx_resource_metric_history_entity_collected_at` on `resource_metric_history` (`entity_id`, `collected_at`);
CREATE INDEX `idx_resource_metric_history_collected_scope_entity` on `resource_metric_history` (`collected_at`, `scope`, `entity_id`);
CREATE TABLE `users` (`id` integer not null primary key autoincrement, `full_name` varchar(255) null, `email` varchar(254) not null, `password` varchar(255) not null, `is_active` boolean not null default '0', `is_admin` boolean not null default '0', `created_at` datetime not null, `updated_at` datetime null);
CREATE UNIQUE INDEX `users_email_unique` on `users` (`email`);
CREATE TABLE `auth_access_tokens` (`id` integer not null primary key autoincrement, `tokenable_id` integer not null, `type` varchar(255) not null, `name` varchar(255) null, `hash` varchar(255) not null, `abilities` text not null, `created_at` datetime, `updated_at` datetime, `last_used_at` datetime null, `expires_at` datetime null, foreign key(`tokenable_id`) references `users`(`id`) on delete CASCADE);
CREATE TABLE `system_settings` (`id` integer not null primary key autoincrement, `name` varchar(100) not null, `value` text not null, `created_at` datetime not null, `updated_at` datetime not null);
CREATE UNIQUE INDEX `system_settings_name_unique` on `system_settings` (`name`);
CREATE INDEX `idx_system_settings_name` on `system_settings` (`name`);
CREATE TABLE IF NOT EXISTS "audit_logs" (`id` integer not null primary key autoincrement, `action` varchar(64) not null, `entity_type` varchar(32) not null, `entity_id` integer null, `entity_name` varchar(255) null, `description` text not null, `details` text null, `ip_address` varchar(45) null, `user_agent` varchar(500) null, `status` text check (`status` in ('success', 'failure', 'warning')) not null default 'success', `error_message` text null, `created_at` datetime not null);
CREATE INDEX `idx_audit_action` on `audit_logs` (`action`);
CREATE INDEX `idx_audit_entity_type` on `audit_logs` (`entity_type`);
CREATE INDEX `idx_audit_entity_id` on `audit_logs` (`entity_id`);
CREATE INDEX `idx_audit_status` on `audit_logs` (`status`);
CREATE INDEX `idx_audit_created` on `audit_logs` (`created_at`);
CREATE INDEX `idx_audit_entity` on `audit_logs` (`entity_type`, `entity_id`);
